### ISSUE TITLE
I think your project includes an outdated Sarissa version.

### ISSUE THREAD

**Issue by volkertb** [plone/plone.app.sarissa#1]
Hi,

I noticed your project probably using an outdated version of the Sarissa JavaScript/AJAX library. The version in your code base has no resolved version number, which leads me to suspect that you extracted it from the (unprocessed) src folder from a CVS checkout from SourceForge. The code in the version you use does not explicitly check for IE9 or later IE versions. The latest official version is 0.9.9.6 and it includes some fixes for IE9, among other things. Even that version is old and outdated. I exported the latest CVS trunk version from the official SourceForge CVS repository and exported it to Git and pushed it to GitHub. I made some fixes to the project's Maven POM and I'm trying to collect good quality third party patches for inclusion into the 0.9.9.7-SNAPSHOT branch that I started today. If you are still maintaining any projects that rely on Sarissa in any way, you might want to take a look: https://github.com/volkertb/sarissa/tree/0.9.9.7-SNAPSHOT

I don't know if you are still actively maintaining this project, but just in case, I thought I'd let you know.

Keep on coding and having fun! :-)

**Comment by thet** [comment]
Thank you for bringing this up! I searched through github and looked at our current versions file. It looks like, plone.app.sarissa is nowhere used anymore.
I'll close this as "wontfix".
However, if someone needs this, here is a reference that this package is outdated.
